#!/system/bin/sh
ui_print "Hunter Environment Stealth"
ui_print "- Runtime files are applied during post-fs-data"
ui_print "- property profile is generated by local propctl"
ui_print "- property profile is applied by global bind mounts"
ui_print "- Reboot after installation"
